class Sprite{
    constructor(title, id, name, image, type){
        this.title = title;
        this.id = id;
        this.name = name;
        this.image = image;
        this.type = type;
    }
}

var sprites = [
    new Sprite('Burst', 0, 'Burst', 'img/sprites/Burst.png', 'SpellSpeed'),
    new Sprite('Barrier', 1, 'Barrier', 'img/sprites/Barrier.png', 'Keyword'),
    new Sprite('Imbue', 2, 'Imbue', 'img/sprites/Imbue.png', 'Card Effect'),
    new Sprite('Scout', 3, 'Scout', 'img/sprites/Scout.png', 'Keyword'),
    new Sprite('Augment', 4, 'Augment', 'img/sprites/Augment.png', 'Keyword'),
    new Sprite('Attach', 5, 'Attach', 'img/sprites/Attach.png', 'Keyword'),
    new Sprite('Level up: full', 6, 'ChampLevelUpIcon3', 'img/sprites/ChampLevelUpIcon3.png', 'Levelup'),    
    new Sprite('Aura', 7, 'Aura', 'img/sprites/Aura.png', 'Keyword'),
    new Sprite('Generic trigger', 8, 'GenericTrigger', 'img/sprites/GenericTrigger.png', 'Card Effect'),
    new Sprite('Regeneration', 9, 'Regeneration', 'img/sprites/Regeneration.png', 'Keyword'),
    new Sprite('Spell Shield', 10, 'SpellShield', 'img/sprites/SpellShield.png', 'Keyword'),
    new Sprite('Fated', 11, 'Fated', 'img/sprites/Fated.png', 'Keyword'),
    new Sprite('Formidable', 12, 'Formidable', 'img/sprites/Formidable.png', 'Keyword'),
    new Sprite('Stardust', 13, 'Stardust', 'img/sprites/Stardust.png', 'Currency'),
    new Sprite('Level up: half', 14, 'ChampLevelUpIcon2', 'img/sprites/ChampLevelUpIcon2.png', 'Levelup'),
    new Sprite('Attune', 15, 'Attune', 'img/sprites/Attune.png', 'Keyword'),
    new Sprite('Frostbite', 16, 'Frostbite', 'img/sprites/Frostbite.png', 'Keyword'),
    new Sprite('Reckless', 17, 'Reckless', 'img/sprites/Reckless.png', 'Keyword'),
    new Sprite('Fury', 18, 'Fury', 'img/sprites/Fury.png', 'Keyword'),
    new Sprite('Lurk', 19, 'Lurk', 'img/sprites/Lurk.svg', 'Keyword'),
    new Sprite('Impact', 20, 'Impact', 'img/sprites/Impact.png', 'Keyword'),
    new Sprite('Impact: empty', 21, 'Impact: empty', 'img/sprites/Impact_Base.png', 'Keyword'),
    new Sprite('Level up: empty', 22, 'ChampLevelUpIcon1', 'img/sprites/ChampLevelUpIcon1.png', 'Levelup'),
    new Sprite('Champion wildcard', 23, 'champion', 'img/sprites/champion.png', 'Wildcard'),
    new Sprite('Fleeting', 24, 'Fleeting', 'img/sprites/Fleeting.png', 'Keyword'),
    new Sprite('Quick strike', 25, 'QuickStrike', 'img/sprites/QuickStrike.png', 'Keyword'),
    new Sprite('Silenced', 26, 'Silenced', 'img/sprites/Silenced.png', 'Keyword'),
    new Sprite('Stunned', 27, 'Stunned', 'img/sprites/Stunned.png', 'Keyword'),
    new Sprite('Tough', 28, 'Tough', 'img/sprites/Tough.png', 'Keyword'),
    new Sprite('Vulnerable', 29, 'Vulnerable', 'img/sprites/Vulnerable.png', 'Keyword'),
    new Sprite('Bandle city', 30, '', 'img/sprites/BandleCity.png', 'Region'),
    new Sprite('Epic wildcard', 31, 'epic', 'img/sprites/epic.png', 'Wildcard'),
    new Sprite('Fearsome', 32, 'Fearsome', 'img/sprites/Fearsome.png', 'Keyword'),
    new Sprite('Immobile', 33, 'Immobile', 'img/sprites/Immobile.png', 'Keyword'),
    new Sprite('Last breath', 34, 'LastBreath', 'img/sprites/LastBreath.png', 'Keyword'),
    new Sprite('Lifesteal', 35, 'Lifesteal', 'img/sprites/Lifesteal.png', 'Keyword'),
    new Sprite('Overwhelm', 36, 'Overwhelm', 'img/sprites/Overwhelm.png', 'Keyword'),
    new Sprite('Attack skill mark', 37, 'AttackSkillMark', 'img/sprites/AttackSkillMark.png', 'Card Effect'),
    new Sprite('Play skill mark', 38, 'PlaySkillMark', 'img/sprites/PlaySkillMark.png', 'Card Effect'),
    new Sprite('Shurima', 39, 'Shurima', 'img/sprites/Shurima.png', 'Region'),
    new Sprite('Rare wildcard', 40, 'rare', 'img/sprites/rare.png', 'Wildcard'),
    new Sprite('Capture', 41, 'Capture', 'img/sprites/Capture.png', 'Keyword'),
    new Sprite('Challenger', 42, 'Challenger', 'img/sprites/Challenger.png', 'Keyword'),
    new Sprite('Deep', 43, 'Deep', 'img/sprites/Deep.png', 'Keyword'),
    new Sprite('Double strike', 44, 'DoubleStrike', 'img/sprites/DoubleStrike.png', 'Keyword'),
    new Sprite('Elusive', 45, 'Elusive', 'img/sprites/Elusive.png', 'Keyword'),
    new Sprite('Ephemeral', 46, 'Ephemeral', 'img/sprites/Ephemeral.png', 'Keyword'),
    new Sprite('Targon', 47, 'Targon', 'img/sprites/Targon.png', 'Region'),
    new Sprite('Fast', 48, 'Fast', 'img/sprites/Fast.png', 'SpellSpeed'),
    new Sprite('Slow', 49, 'Slow', 'img/sprites/Slow.png', 'SpellSpeed'),
    new Sprite('Focus', 50, 'Focus', 'img/sprites/Focus.png', 'SpellSpeed'),    //TODO
    new Sprite('Landmark', 51, 'LandmarkVisualOnly', 'img/sprites/LandmarkVisualOnly.png', 'Keyword'),
    new Sprite('Coin', 52, 'currency_bp', 'img/sprites/currency_bp.png', 'Currency'),
    new Sprite('Shards', 53, 'currency_shards', 'img/sprites/currency_shards.png', 'Currency'),
    new Sprite('Common wildcard', 54, 'common', 'img/sprites/common.png', 'Wildcard'),
    new Sprite('All regions', 55, 'AllFactions', 'img/sprites/Runeterra.png', 'Region'),
    new Sprite('Bilgewater', 56, 'Bilgewater', 'img/sprites/Bilgewater.png', 'Region'),
    new Sprite('Demacia', 57, 'Demacia', 'img/sprites/Demacia.png', 'Region'),
    new Sprite('Freljord', 58, 'Freljord', 'img/sprites/Freljord.png', 'Region'),
    new Sprite('Ionia', 59, 'Ionia', 'img/sprites/Ionia.png', 'Region'),
    new Sprite('Noxus', 60, 'Noxus', 'img/sprites/Noxus.png', 'Region'),
    new Sprite('Piltover', 61, 'PiltoverZaun', 'img/sprites/PiltoverZaun.png', 'Region'),
    new Sprite('Shadow isles', 62, 'ShadowIsles', 'img/sprites/ShadowIsles.png', 'Region'),
    new Sprite('Runeterra','' , 'Runeterra', 'img/sprites/AllFactions.png', 'Region'),

    new Sprite('Hallowed', '', 'Hallowed', 'img/sprites/Hallowed.png', 'Keyword'),
    new Sprite('Evolve', '', 'Evolve', 'img/sprites/Evolve.png', 'Keyword'),
    new Sprite('Brash', '', 'Brash', 'img/sprites/Brash.svg', 'Keyword'),
    new Sprite('Equipment', '', 'Equipment', 'img/sprites/Equipment.png', 'Keyword'),
    new Sprite('Jhin', '', 'Jhin', 'img/sprites/Jhin.png', 'Origin'),
    new Sprite('Bard', '', 'Bard', 'img/sprites/Bard.png', 'Origin'),
    new Sprite('Evelynn', '', 'Evelynn', 'img/sprites/Evelynn.png', 'Origin'),
    new Sprite('Jax', '', 'Jax', 'img/sprites/Jax.png', 'Origin'),
    new Sprite('Kayn', '', 'Kayn', 'img/sprites/Kayn.png', 'Origin'),
    new Sprite('Varus', '', 'Varus', 'img/sprites/Varus.png', 'Origin'),
    new Sprite('Ryze', '', 'Ryze', 'img/sprites/Ryze.png', 'Origin'),
    new Sprite('Aatrox', '', 'Aatrox', 'img/sprites/Aatrox.png', 'Origin'),
    new Sprite('PoroKing', '', 'PoroKing', 'img/sprites/PoroKing.png', 'Origin'),
    new Sprite('Neeko', '', 'Neeko', 'img/sprites/Neeko.png', 'Region'),
    new Sprite('Elemental Skill', '', 'ElementalSkill', 'img/sprites/ElementalSkill.png', 'Card Effect'),
    new Sprite('Elder Dragon', '', 'ElderDragon', 'img/sprites/ElderDragon.png', 'Region'),
    new Sprite('Curse', '', 'Curse', 'img/sprites/Curse.png', 'Keyword'),
    new Sprite('Deathless', '', 'Deathless', 'img/sprites/Deathless.png', 'Keyword'),
    // new Sprite('Void', 2, '', 'img/sprites/Void.png', 'Region'),
    // new Sprite('Zaun', 20, '', 'img/sprites/Zaun.png','Region'),
    // new Sprite('Bandle city', 10, '', 'img/sprites/BandleCity.png', 'Region'),
];
